### ISSUE TITLE
Core updates

### ISSUE THREAD

**Issue by UpTil4Music** [zirafa/pushtape-drops-7#1]
Trying your distribution on Pantheon, looks like some interesting features. Will you be updating core anytime soon?
![coreupdates](https://cloud.githubusercontent.com/assets/8726490/4364035/fd1abf3c-429b-11e4-987a-48586ace8dc0.png)

**Comment by zirafa** [comment]
I believe Pantheon already does automated core updates, but I'll try and be better about syncing this repo more regularly. http://drupal.org/project/pushtape is usually where the most up-to-date package lives, this repo is more like a mirror. As you can probably tell, I also check the Drupal issue queue more regularly than this issue queue.

**Comment by zirafa** [comment]
(BTW this repo was updated just a few days ago with core + contrib updates.)
